services:
  # PHP Service
  php:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        user: ${WORKSPACE_USER}
        uid: 1000
        php_version: ${WORKSPACE_PHP_VERSION}
        composer_version: ${WORKSPACE_COMPOSER_VERSION}
    image: laravel-app
    container_name: php
    tty: true
    environment:
      SERVICE_NAME: app
      SERVICE_TAGS: dev
    working_dir: /var/www
    volumes:
      - ${PHP_WORKSPACE}:/var/www
      - ~/.ssh:/home/${WORKSPACE_USER}/.ssh:ro
      - ./cache/composer:/home/${WORKSPACE_USER}/.composer/cache
      - ./config/php/local.ini:/usr/local/etc/php/conf.d/local.ini
      - vscode_workspace_data:/home/${WORKSPACE_USER}/.vscode-server
    networks:
      - app-network

  # Nginx Service
  nginx:
    image: nginx:alpine
    container_name: nginx
    tty: true
    ports:
      - "${WEB_SERVER_HTTP_PORT}:80"
      - "${WEB_SERVER_HTTPS_PORT}:443"
    volumes:
      - ${PHP_WORKSPACE}:/var/www
      - ./config/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./config/nginx/conf.d:/etc/nginx/conf.d
      - ./config/nginx/certs:/etc/nginx/certs
    entrypoint:
      - "nginx"
    command: [ "-g", "daemon off;" ]
    networks:
      app-network:
        aliases:
          - php_api.docker

  # MySQL Service
  mysql:
    image: ${DATABASE_IMAGE}:${DATABASE_VERSION}
    container_name: mysql
    tty: true
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${DATABASE_ROOT_PASSWORD}
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
      TZ: Asia/Yangon
    volumes:
      - ${DATABASE_STORE}:/var/lib/mysql/
      - ./config/mysql/my.cnf:/etc/mysql/my.cnf
    networks:
      - app-network

  # PHP myadmin service
  phpmyadmin:
    image: phpmyadmin:${PHPMYADMIN_VER}
    container_name: phpmyadmin
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      PMA_ARBITRARY: 0
      PMA_USER: root
      PMA_PASSWORD: ${DATABASE_ROOT_PASSWORD}
      HIDE_PHP_VERSION: "true"
    ports:
      - "${PHPMYADMIN_PORT}:80"
    networks:
      - app-network

  # Redis service
  redis:
    image: redis:${REDIS_VERSION}
    container_name: redis
    ports:
      - "${REDIS_PORT}:6379"
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - redis_data:/var/lib/redis/
    networks:
      - app-network

  # Nodejs service
  nodejs:
    build:
      context: .
      dockerfile: node/Dockerfile
      args:
        NODE_VERSION: ${NODE_VERSION}
        Y_V: ${YARN_VERSION}
    container_name: nodejs
    tty: true
    ports:
      - "3000:3000"
      - "4200:4200"
    volumes:
      - ${NODE_WORKSPACE}:/var/www
      - ~/.ssh:/home/node/.ssh:ro
      - ./cache/npm:/home/node/.npm
      - ./cache/yarn:/home/node/.yarn
      - vscode_nodejs_data:/home/node/.vscode-server
    networks:
      - app-network

  # Golang service
  golang:
    build:
      context: .
      dockerfile: golang/Dockerfile
      args:
        user: ${WORKSPACE_USER}
        uid: 1000
        golang_version: ${GOLANG_VERSION}
        go_path: ${GOLANG_WORKSPACE_GOPATH}
    image: golang
    container_name: golang
    tty: true
    working_dir: /var/www
    volumes:
      - ${GO_PATH_DATA}:${GOLANG_WORKSPACE_GOPATH}
      - ${GOLANG_WORKSPACE}:/var/www
      - vscode_golang_data:/home/${WORKSPACE_USER}/.vscode-server
    ports:
      - "8008:8008"
      - "9009:9009"
    networks:
      - app-network

  # Python service
  python:
    build:
      context: .
      dockerfile: python/Dockerfile
      args:
        user: ${WORKSPACE_USER}
        uid: 1000
        python_version: ${PYTHON_VERSION}
    image: python
    container_name: python
    tty: true
    working_dir: /var/www
    volumes:
      - ${PYTHON_WORKSPACE}:/var/www
      - vscode_python_data:/home/${WORKSPACE_USER}/.vscode-server
    ports:
      - "8081:8081"
      - "9091:9091"
    networks:
      - app-network

  # Rabbitmq service
  rabbitmq:
    build:
      context: .
      dockerfile: rabbitmq/Dockerfile
      args:
        RABBITMQ_VERSION: ${RABBITMQ_VERSION}
    container_name: rabbitmq
    image: rabbitmq
    ports:
      - "${RABBITMQ_NODE_HOST_PORT}:5672"
      - "${RABBITMQ_MANAGEMENT_HTTP_HOST_PORT}:15672"
      - "${RABBITMQ_MANAGEMENT_HTTPS_HOST_PORT}:15671"
    environment:
      SERVICE_NAME: rabbitmq
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_DEFAULT_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_DEFAULT_PASS}
    volumes:
      - ${RABBITMQ_STORE}:/var/lib/rabbitmq
    networks:
      - app-network

#Docker Networks
networks:
  app-network:
    driver: bridge

# Volumes
volumes:
  vscode_workspace_data:
    driver: local
  db_data:
    driver: local
  redis_data:
    driver: local
  go_path_data:
    driver: local
  vscode_nodejs_data:
    driver: local
  vscode_golang_data:
    driver: local
  vscode_python_data:
    driver: local
  rabbitmq_data:
    driver: local
